routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UserController::class, 'index'])->name('user');

Route::get('/books', [BookController::class, 'index'])->name('book');
Route::get('/books/create', [BookController::class, 'create'])->name('book.create');
Route::post('/books', [BookController::class, 'store']);
Route::get('/books/{book:slug}___{randomStr}/file', [BookController::class, 'file'])->name('book.file');
Route::get('/books/{book:slug}/edit', [BookController::class, 'edit'])->name('book.edit');
Route::put('/books/{book:slug}', [BookController::class, 'update'])->name('book.update');
Route::delete('/books/{book:slug}', [BookController::class, 'destroy'])->name('book.delete');

Route::get('/articles', [ArticleController::class, 'index'])->name('article');
Route::get('/articles/create', [ArticleController::class, 'create'])->name('article.create');
Route::post('/articles', [ArticleController::class, 'store']);
Route::get('/articles/{article:slug}/edit', [ArticleController::class, 'edit'])->name('article.edit');
Route::put('/articles/{article:slug}', [ArticleController::class, 'update'])->name('article.update');
Route::delete('/articles/{article:slug}', [ArticleController::class, 'destroy'])->name('article.delete');

Route::get('/orders', [OrderController::class, 'index'])->name('order');
Route::get('/orders/{order:invoice}', [OrderController::class, 'show'])->name('order.show');
Route::post('/orders/{order:invoice}/confirm', [OrderController::class, 'confirmPayment'])->name('order.confirm');

routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MyBookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::view('/privasi', 'privasi')->name('privasi');

Route::get('/buku', [BookController::class, 'index'])->name('book');
Route::get('/buku/query', [BookController::class, 'query'])->name('book.query');
Route::get('/buku/{book:slug}', [BookController::class, 'show'])->name('book.detail');

Route::get('/berita', [ArticleController::class, 'index'])->name('article');
Route::get('/berita/{article:slug}', [ArticleController::class, 'show'])->name('article.show');

Route::middleware('auth')->group(function () {
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add/{book:slug}', [CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/remove/{book:slug}', [CartController::class, 'remove'])->name('cart.remove');

//    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('checkout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/user', [DashboardController::class, 'user'])->name('dashboard.user');

    Route::get('/kelola/buku-saya', [MyBookController::class, 'index'])->name('my-book');
    Route::get('/kelola/buku-saya/{id}___{randomStr}/file', [MyBookController::class, 'file'])->name('my-book.file');
    Route::get('/kelola/buku-saya/{id}/view', [MyBookController::class, 'view'])->name('my-book.view');

    Route::get('/kelola/transaksi', [TransactionController::class, 'index'])->name('transaction');
    Route::get('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'detail'])->name('transaction.detail');
    Route::post('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'payment']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile');
    Route::put('/profile', [ProfileController::class, 'update']);
});

Route::middleware('admin')
    ->prefix('admin')
    ->name('admin.')->group(function () {
        require __DIR__ . '/admin.php';
    });

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    public function __construct(public string|null $title = null)
    {
        //
    }

    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/DashboardLayout.php
<?php

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class DashboardLayout extends Component
{
    public function __construct(public string|null $pageTitle = null)
    {
        //
    }

    public function render(): View
    {
        return view('layouts.dashboard');
    }
}

resources/views/cart.blade.php
<x-app-layout title="Keranjang">
    <div class="container mx-auto">
        <div class="flex gap-x-3 my-10">
            <div class="w-full rounded-lg border shadow-lg px-5">
                <div class="overflow-x-auto">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Item</th>
                            <th>Judul Buku</th>
                            <th>Kategori</th>
                            <th>Harga</th>
                            <th>Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(count($cart) === 0)
                            <td colspan="5" class="text-center">Tidak ada buku di dalam keranjang.</td>
                        @endif
                        @foreach($cart as $cartBook)
                            <tr>
                                <td><img class="w-20" src="{{ $cartBook->book->image_url }}" alt="{{ $cartBook->book->title }}"></td>
                                <td>{{ $cartBook->book->title }}</td>
                                <td>{{ $cartBook->book->category->name }}</td>
                                <td>{{ rupiah($cartBook->book->price) }}</td>
                                <td>
                                    <div class="flex justify-center items-center rounded-md w-9 h-9 bg-accent text-white">
                                        <a href="{{ route('cart.remove', $cartBook->book->slug) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                            </svg>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="max-w-xs w-full rounded-lg h-fit border shadow-lg px-5 pt-3 pb-8">
                <h2 class="text-center text-xl font-bold">Ringkasan Pesanan</h2>
                <div class="flex justify-between items-center mt-3 border-b">
                    <span class="text-md">Total Item</span>
                    <span class="text-md font-bold">{{ count($cart) }}</span>
                </div>
                <div class="flex justify-between items-center mt-3 border-b">
                    <span class="text-md">Total</span>
                    <span class="text-md font-bold">{{ rupiah($total) }}</span>
                </div>
                <div class="flex flex-col items-center gap-y-2 mt-5">
                    <a href="{{ route('checkout') }}" class="btn btn-sm btn-accent text-white" @if(count($cart) === 0) disabled @endif>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Z" />
                        </svg>
                        Checkout
                    </a>
                    <a href="{{ route('home') }}" class="btn btn-sm btn-accent text-white">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
                        </svg>
                        Lanjut Belanja
                    </a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/checkout.blade.php
<x-app-layout title="Checkout">
    <div class="container mx-auto">
        <form class="flex gap-x-3 my-10" method="post">
            @csrf
            <div class="w-full rounded-lg border shadow-lg px-5 py-3">
                <h2 class="text-xl font-bold">Pilih Metode Pembayaran</h2>
                <h3 class="text-lg font-bold mt-5">Transfer Manual</h3>
                <div class="grid grid-cols-3 gap-10">
                    @foreach($banks as $bank)
                        <div class="form-control">
                            <label class="label justify-start gap-x-3 cursor-pointer">
                                <input type="radio" name="bank" class="radio checked:bg-red-500" value="{{ $bank->id }}" required />
                                <span class="label-text">
                                    <img class="w-20" src="{{ asset($bank->image) }}" alt="{{ $bank->name }}">
                                </span>
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="max-w-xs w-full rounded-lg h-fit border shadow-lg px-5 pt-3 pb-8">
                <h2 class="text-center text-xl font-bold">Ringkasan Pesanan</h2>
                <div class="flex justify-between items-center mt-3 border-b">
                    <span class="text-md">Total Item</span>
                    <span class="text-md font-bold">{{ count($cart) }}</span>
                </div>
                <div class="flex justify-between items-center mt-3 border-b">
                    <span class="text-md">Total</span>
                    <span class="text-md font-bold">{{ rupiah($total) }}</span>
                </div>
                <div class="flex flex-col items-center gap-y-2 mt-5">
                    <button type="submit" class="btn btn-sm btn-accent text-white" @if(count($cart) === 0) disabled @endif>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Z" />
                        </svg>
                        Bayar
                    </button>
                </div>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/dashboard.blade.php
<x-dashboard-layout page-title="Dashboard">
    <div class="container mx-auto py-10">
        <div class="flex gap-x-3 w-full shadow rounded-md p-5 bg-base-100">
            <div class="flex justify-center items-center w-16 h-16 rounded-md bg-error text-white">
                <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
                </svg>
            </div>
            <div class="flex flex-col justify-center">
                <h2 class="text-md font-light mb-1">Total Buku</h2>
                <h3 class="text-xl font-bold">{{ $bookCount }}</h3>
            </div>
        </div>
        <div class="flex gap-x-3 w-full shadow rounded-md mt-5 p-5 bg-base-100">
            <div class="flex justify-center items-center w-16 h-16 rounded-md bg-secondary text-white">
                <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
                </svg>
            </div>
            <div class="flex flex-col justify-center">
                <h2 class="text-md font-light mb-1">Buku Saya</h2>
                <a href="{{ route('my-book') }}" class="flex items-center gap-x-1 text-lg font-bold hover:text-secondary">
                    Lihat
                    <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                    </svg>
                </a>
            </div>
        </div>
    </div>
</x-dashboard-layout>

resources/views/home.blade.php
<x-app-layout title="Home">
    <div id="hero" class="flex justify-center items-center w-full">
        <div class="w-fit py-24">
            <h1 class="uppercase text-center text-4xl font-bold text-black"><span class="bg-white">Buku</span> <br> <span class="bg-white">Digital Nusantara</span></h1>
            <h2 class="uppercase text-center text-lg font-bold mt-3 px-8 rounded-full text-white bg-gray-500">Literasi dan Informasi Dalam Genggaman</h2>
        </div>
    </div>
    <div class="w-full max-w-3xl mx-auto -mt-14 rounded-lg border-4 border-gray-500 bg-white">
        <h3 class="text-center text-2xl font-bold text- my-2">Temukan buku sesuai minat dan kebutuhan kamu !</h3>
        <form action="{{ route('book') }}" class="flex space-x-5 mx-3 my-5">
            <select name="category" class="select select-bordered w-full max-w-40 bg-[#fff3cd]" aria-label="Kategori">
                <option disabled selected>Kategori</option>
                @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
            <select name="price" class="select select-bordered w-full max-w-40 bg-[#fff3cd]" aria-label="Harga">
                <option disabled selected>Harga</option>
                <option value="lte_50000"><50.000</option>
                <option value="lte_100000"><100.000</option>
                <option value="gte_100000">>100.000</option>
            </select>
            <div class="flex items-center w-full">
                <input type="text" name="search" placeholder="Search..." class="input input-bordered w-full rounded-r-none bg-[#fff3cd] placeholder-inherit" aria-label="Search" required />
                <button class="btn btn-outline btn-info rounded-l-none">Search</button>
            </div>
        </form>
    </div>
    <div class="mt-10">
        <h2 class="text-center text-3xl font-bold">Produk Kami</h2>
        <h3 class="text-center text-xl font-bold">Kami menjual buku-buku berkualitas dan terpercaya !</h3>
    </div>
    <div class="flex flex-col items-center container mx-auto mt-3" x-data="">
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-5">
            @foreach($latestBooks as $book)
                <a href="{{ route('book.detail', $book->slug) }}" class="card card-compact bg-base-100 shadow-xl">
                    <figure class="">
                        <img class="h-full" src="{{ $book->image_url }}" alt="{{ $book->title }}" />
                    </figure>
                    <div class="card-body">
                        <div class="tooltip tooltip-bottom before:text-left" data-tip="{{ $book->title }}">
                            <h2 class="font-bold text-lg text-ellipsis whitespace-nowrap overflow-hidden">{{ $book->title }}</h2>
                        </div>
                        <span class="block text-center text-rose-950">{{ $book->category->name }}</span>
                        <span class="block text-center text-rose-700">{{ rupiah($book->price) }}</span>
                    </div>
                </a>
            @endforeach
        </div>

        <a href="{{ route('book') }}" class="mt-6 btn btn-warning">Lihat Produk Lainya</a>
    </div>

    <div class="my-12"></div>
</x-app-layout>

resources/views/privasi.blade.php
<x-app-layout title="Kebijakan dan Privasi">
    <div class="px-16 py-8 text-justify">
        <h1 class="text-3xl text-center font-bold mb-8">Kebijakan dan Privasi</h1>
        <span>Kebijakan dan Privasi di Toko Buku Digital Nusantara</span>

        <h3 class="font-bold mt-6 mb-1">Pengumpulan dan Penggunaan Informasi</h3>
        <ul class="list-disc pl-8">
            <li>Kami dapat mengumpulkan dan menyimpan rincian tentang cara Anda menggunakan layanan kami, termasuk
                permintaan pencarian. Informasi ini dapat digunakan untuk meningkatkan relevansi hasil yang disediakan
                layanan kami. Kecuali dalam kasus tertentu untuk memastikan kualitas layanan kami melalui Internet,
                informasi tersebut tidak akan dikaitkan dengan alamat IP Anda.
            </li>
            <li>Kami dapat mengumpulkan data tentang cara Anda menggunakan perangkat dan aplikasi untuk membantu
                pengembang aplikasi menyempurnakan aplikasi mereka.
            </li>
        </ul>

        <h3 class="font-bold mt-6 mb-1">Akses ke Informasi Pribadi</h3>
        <p>Anda dapat membantu memastikan bahwa informasi kontak dan preferensi Anda sudah akurat, lengkap, dan terbaru
            dengan log in ke akun Anda atau menghubungi kami. Untuk informasi pribadi lain yang kami simpan, kami akan
            memberi Anda akses untuk tujuan apapun, termasuk guna meminta kami mengoreksi data yang tidak akurat jika
            Gramedia Asri Media atau perusahaan afiliasinya dalam Grup Kompas Gramedia tidak wajib menyimpannya
            berdasarkan hukum atau untuk keperluan bisnis yang sah. Kami dapat menolak untuk memproses permintaan yang
            tidak serius/mengganggu, membahayakan privasi orang lain, sangat tidak praktis, atau yang aksesnya tidak
            diwajibkan oleh hukum setempat. Permohonan akses, koreksi dapat diajukan dengan menghubungi kami.
        </p>

        <h3 class="font-bold mt-6 mb-1">Perlindungan Data</h3>
        <p>CV. BUKU DIGITAL NUSANTARA berkomitmen untuk melindungi informasi pribadi pengguna. Kami menerapkan
            langkah-langkah keamanan yang sesuai untuk mencegah akses yang tidak sah dan penggunaan yang tidak sah
            terhadap informasi pribadi.
        </p>

        <h3 class="font-bold mt-6 mb-1">Berbagi Informasi</h3>
        <p>CV. BUKU DIGITAL NUSANTARA tidak akan menyewakan atau menjual informasi pribadi pengguna kepada pihak ketiga
            tanpa izin pengguna, kecuali yang diperlukan untuk memproses transaksi atau sesuai dengan hukum yang
            berlaku.
        </p>

        <h3 class="font-bold mt-6 mb-1">Perubahan Kebijakan Privasi</h3>
        <p>CV. BUKU DIGITAL NUSANTARA dapat memperbarui Kebijakan Privasi ini dari waktu ke waktu. Setiap perubahan akan
            diinformasikan melalui situs web kami. Pengguna diharapkan untuk memeriksa halaman ini secara berkala untuk
            tetap up-to-date.
        </p>

        <h3 class="font-bold mt-6 mb-1">Pernyataan dan Persetujuan</h3>
        <p>Dengan menggunakan Situs-web/Aplikasi/layanan Kami, berarti Anda menyatakan bahwa Anda telah membaca dan
            mengerti Kebijakan Privasi ini dan Ketentuan Penggunaan dan setuju serta memperkenakan Kami untuk
            menggunakan, menerapkan, memproses, dan mengalihkan informasi pribadi Anda sebagaiamana dinyatakan dalam
            Kebijakan Privasi ini.
        </p>
        <p class="mt-3">Anda juga menyatakan bahwa Anda berhak untuk membagikan atas seluruh informasi yang telah
            diberikan kepada
            Kami dan memberikan kepada Kami kewenangan untuk menggunakan dan membagikan informasi pribadi Anda untuk
            mendukung dan melaksanakan produk/layanan Kami.
        </p>

        <div class="my-10 border-b"></div>

        <h3 class="font-bold mt-6 mb-1">Hubungi Kami</h3>
        <p>Jika anda mempunyai pertanyaan atau kepentingan atas Kebijakan Privasi ini atau mengenai penggunaan informasi
            pribadi, hubungi Kami melalui:
        </p>
        <p class="mt-3">CV. Buku Digital Nusantara <br>
            Perumahan PEMDA Jl, Anggur No.24, Tambun - Bekasi <br>
            Email: <a href="mailto:admin@bukudigitalnusantara.com"
                      class="text-blue-600">admin@bukudigitalnusantara.com</a>
        </p>

        <div class="my-10 border-b"></div>
        <p>Dengan menggunakan Situs-web/Aplikasi/layanan Kami, Anda dianggap setuju atas Kebijakan Privasi ini namun
            tidak terbatas pada seluruh perubahannya.
        </p>
    </div>
</x-app-layout>

resources/views/profile.blade.php
<x-dashboard-layout page-title="Profile">
    <div class="container mx-auto">
        <div class="flex gap-x-5">
            <div class="w-fit h-fit bg-base-100 px-5 py-1 rounded shadow-lg">
                <div class="flex flex-col items-center">
                    <div class="flex items-center justify-center rounded-full bg-base-200">
                        <img class="rounded-full w-full" src="{{ Vite::asset('resources/img/avatar.webp') }}" alt="profile" />
                    </div>
                    <span class="block my-5">
                        <span class="font-bold">{{ $user->name }}</span> / <span>{{ $user->is_admin ? 'Admin' : 'Pembaca' }}</span>
                    </span>
                </div>
            </div>
            <form class="w-full bg-base-100 px-7 py-5 rounded shadow-lg" method="post">
                @csrf @method('put')
                <h2 class="font-semibold text-lg">Hi, {{ $user->name }}</h2>
                <span class="block text-sm mt-2">Ubah informasi tentang diri Anda di disini.</span>

                @if(session('success'))
                    <div role="alert" class="alert alert-success mt-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                        <span>{{ session('success') }}</span>
                    </div>
                @endif

                @if ($errors->any())
                    <div role="alert" class="alert alert-error mt-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                        <span>Error! Terjadi kesalahan.</span>
                    </div>
                @endif

                <div class="mt-10">
                    <h2 class="font-semibold text-lg">Data Diri</h2>
                    <div class="divider my-1"></div>
                    <div class="grid grid-cols-2 gap-3">
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Nama</span>
                            </div>
                            <input type="text" name="name" placeholder="Type here" class="input input-bordered w-full max-w-xs @error('name') input-error @enderror" value="{{ old('name') ?? $user->name }}" required />
                            @error('name')
                                <div class="label">
                                    <span class="label-text-alt text-error">{{ $message }}</span>
                                </div>
                            @enderror
                        </label>
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Nomor HP</span>
                            </div>
                            <input type="text" name="phone" placeholder="Type here" class="input input-bordered w-full max-w-xs" value="{{ old('phone') ?? $user->phone }}" {{ $user->is_admin ? '' : 'required' }} />
                        </label>
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Email</span>
                            </div>
                            <input type="email" name="email" placeholder="Type here" class="input input-bordered w-full max-w-xs @error('email') input-error @enderror" value="{{ old('email') ?? $user->email }}" required />
                            @error('email')
                                <div class="label">
                                    <span class="label-text-alt text-error">{{ $message }}</span>
                                </div>
                            @enderror
                        </label>
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Alamat</span>
                            </div>
                            <input type="text" name="address" placeholder="Type here" class="input input-bordered w-full max-w-xs" value="{{ old('address') ?? $user->address }}" {{ $user->is_admin ? '' : 'required' }} />
                        </label>
                    </div>
                </div>
                <div class="mt-10">
                    <h2 class="font-semibold text-lg">Keamanan</h2>
                    <div class="divider my-1"></div>
                    <div class="grid grid-cols-2 gap-3">
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Password</span>
                            </div>
                            <input type="password" name="password" placeholder="Type here" class="input input-bordered w-full max-w-xs @error('password') input-error @enderror" />
                            @error('password')
                                <div class="label">
                                    <span class="label-text-alt text-error">{{ $message }}</span>
                                </div>
                            @enderror
                        </label>
                        <label class="form-control w-full max-w-xs">
                            <div class="label">
                                <span class="label-text">Konfirmasi Password</span>
                            </div>
                            <input type="password" name="password_confirmation" placeholder="Type here" class="input input-bordered w-full max-w-xs @error('password') input-error @enderror" />
                        </label>
                    </div>
                </div>
                <div class="flex justify-end mt-5">
                    <button type="submit" class="btn btn-primary">Perbarui</button>
                </div>
            </form>
        </div>
    </div>
</x-dashboard-layout>