routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UserController::class, 'index'])->name('user');

Route::get('/books', [BookController::class, 'index'])->name('book');
Route::get('/books/create', [BookController::class, 'create'])->name('book.create');
Route::post('/books', [BookController::class, 'store']);
Route::get('/books/{book:slug}___{randomStr}/file', [BookController::class, 'file'])->name('book.file');
Route::get('/books/{book:slug}/edit', [BookController::class, 'edit'])->name('book.edit');
Route::put('/books/{book:slug}', [BookController::class, 'update'])->name('book.update');
Route::delete('/books/{book:slug}', [BookController::class, 'destroy'])->name('book.delete');

Route::get('/articles', [ArticleController::class, 'index'])->name('article');
Route::get('/articles/create', [ArticleController::class, 'create'])->name('article.create');
Route::post('/articles', [ArticleController::class, 'store']);
Route::get('/articles/{article:slug}/edit', [ArticleController::class, 'edit'])->name('article.edit');
Route::put('/articles/{article:slug}', [ArticleController::class, 'update'])->name('article.update');
Route::delete('/articles/{article:slug}', [ArticleController::class, 'destroy'])->name('article.delete');

Route::get('/orders', [OrderController::class, 'index'])->name('order');
Route::get('/orders/{order:invoice}', [OrderController::class, 'show'])->name('order.show');
Route::post('/orders/{order:invoice}/confirm', [OrderController::class, 'confirmPayment'])->name('order.confirm');

routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MyBookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::view('/privasi', 'privasi')->name('privasi');

Route::get('/buku', [BookController::class, 'index'])->name('book');
Route::get('/buku/query', [BookController::class, 'query'])->name('book.query');
Route::get('/buku/{book:slug}', [BookController::class, 'show'])->name('book.detail');

Route::get('/berita', [ArticleController::class, 'index'])->name('article');
Route::get('/berita/{article:slug}', [ArticleController::class, 'show'])->name('article.show');

Route::middleware('auth')->group(function () {
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add/{book:slug}', [CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/remove/{book:slug}', [CartController::class, 'remove'])->name('cart.remove');

//    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('checkout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/user', [DashboardController::class, 'user'])->name('dashboard.user');

    Route::get('/kelola/buku-saya', [MyBookController::class, 'index'])->name('my-book');
    Route::get('/kelola/buku-saya/{id}___{randomStr}/file', [MyBookController::class, 'file'])->name('my-book.file');
    Route::get('/kelola/buku-saya/{id}/view', [MyBookController::class, 'view'])->name('my-book.view');

    Route::get('/kelola/transaksi', [TransactionController::class, 'index'])->name('transaction');
    Route::get('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'detail'])->name('transaction.detail');
    Route::post('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'payment']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile');
    Route::put('/profile', [ProfileController::class, 'update']);
});

Route::middleware('admin')
    ->prefix('admin')
    ->name('admin.')->group(function () {
        require __DIR__ . '/admin.php';
    });

require __DIR__ . '/auth.php';

app/Models/Book.php
<?php

namespace App\Models;

use App\Traits\GenerateSlug;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Umutphp\LaravelModelRecommendation\HasRecommendation;
use Umutphp\LaravelModelRecommendation\InteractWithRecommendation;

class Book extends Model implements InteractWithRecommendation
{
    use HasFactory, GenerateSlug, HasRecommendation;

    protected $guarded = [];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function imageUrl(): Attribute
    {
        return Attribute::get(function () {
            if (Str::startsWith($this->image, 'http')) {
                return $this->image;
            }

            return Storage::url($this->image);
        });
    }

    public static function getRecommendationConfig(): array
    {
        return [
            'similar_books' => [
                'recommendation_algorithm' => 'similarity',
                'similarity_feature_weight' => 3,
                'similarity_numeric_value_weight' => 0.5,
                'similarity_numeric_value_high_range' => 20,
                'similarity_taxonomy_weight' => 2,
                'similarity_feature_attributes' => [
                    'author'
                ],
                'similarity_numeric_value_attributes' => [
                    'price'
                ],
                'similarity_taxonomy_attributes' => [
                    [
                        'category' => 'name',
                    ]
                ],
                'recommendation_count' => 5,
                'recommendation_order' => 'desc',
            ],
            'sold_together' => [
                'recommendation_algorithm'         => 'db_relation',
                'recommendation_data_table'        => 'order_details',
                'recommendation_data_table_filter' => [],
                'recommendation_data_field'        => 'book_id',
                'recommendation_data_field_type'   => self::class,
                'recommendation_group_field'       => 'order_id',
                'recommendation_count'             => 5
            ],
        ];
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class BookController extends Controller
{
    private function getBookRequestData(Request $request): array
    {
        $data = [
            'category_id' => $request->input('category_id'),
            'title' => $request->input('title'),
            'slug' => Str::slug($request->input('title')),
            'description' => $request->input('description'),
            'author' => $request->input('author'),
            'price' => $request->input('price'),
        ];

        if ($request->hasFile('image')) {
            $data['image'] = $request->file('image')->storePublicly('public/books-image');
        }

        if ($request->hasFile('book_file')) {
            $data['file_path'] = $request->file('book_file')->store('book-file');
        }

        return $data;
    }

    public function index(Request $request): View
    {
        $query = Book::with('category');

        if ($keyword = $request->input('search')) {
            $query = $query->where('title', 'like', "%{$keyword}%");
        }

        $books = $query->orderBy('id', 'desc')->paginate(15);

        return view('admin.book.index', compact('books'));
    }

    public function create(): View
    {
        $book = null;
        $categories = Category::query()->get()->all();

        return view('admin.book.form', compact('book', 'categories'));
    }

    public function store(Request $request): RedirectResponse
    {
        Book::query()->create($this->getBookRequestData($request));

        return redirect()
            ->route('admin.book')
            ->with(['success' => 'Berhasil menambahkan data buku.']);
    }

    public function file(Book $book, string $randomStr): BinaryFileResponse
    {
        return response()->file(Storage::path($book->file_path), [
            'Content-Disposition' => 'inline; filename="' . $book->title . '.pdf"',
        ]);
    }

    public function edit(Book $book): View
    {
        $categories = Category::query()->get()->all();

        return view('admin.book.form', compact('book', 'categories'));
    }

    public function update(Book $book, Request $request): RedirectResponse
    {
        $book->update($this->getBookRequestData($request));

        return redirect()
            ->route('admin.book')
            ->with(['success' => 'Berhasil mengubah data buku.']);
    }

    public function destroy(Book $book): RedirectResponse
    {
        Storage::delete($book->image);
        Storage::delete($book->file_path);

        $book->delete();

        return redirect()
            ->route('admin.book')
            ->with(['success' => 'Berhasil menghapus data buku.']);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use App\Models\UserBook;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BookController extends Controller
{
    public function index(Request $request): View|RedirectResponse
    {
        $categories = Category::query()->get()->all();

        $price = $request->input('price');

        if (!empty($price)) {
            $queryParams = $request->only('search', 'category');

            $priceExpl = explode('_', $price);

            if ($priceExpl[0] === 'lte') {
                $queryParams['max_price'] = $priceExpl[1];
            } else {
                $queryParams['min_price'] = $priceExpl[1];
            }

            return redirect()->route('book', $queryParams);
        }

        return view('book.index', compact('categories'));
    }

    public function query(Request $request): JsonResponse
    {
        $query = Book::with('category')
            ->select('category_id', 'image', 'title', 'slug', 'price', 'author');

        if ($request->has('search')) {
            $query = $query->where('title', 'like', '%' . $request->input('search') . '%');
        }

        if ($minPrice = $request->input('min_price') and !empty($minPrice)) {
            $query = $query->where('price', '>=', $minPrice);
        }

        if ($maxPrice = $request->input('max_price') and !empty($maxPrice)) {
            $query = $query->where('price', '<=', $maxPrice);
        }

        if ($categories = $request->input('categories')) {
            if (is_array($categories) && !empty($categories)) {
                $query = $query->whereIn('category_id', $categories);
            }
        }

        $data = $query->orderBy('id', 'desc')->paginate(12);

        foreach ($data->items() as $book) {
            $book['image_url'] = $book->image_url;
            $book['price_rupiah'] = rupiah($book->price);
        }

        return response()->json($data);
    }

    public function show(Book $book): View
    {
        $book->update(['views' => $book->views + 1]);
        $relatedBooks = $book->getRecommendations('similar_books');

        $soldCount = UserBook::query()
            ->where('book_id', $book->id)
            ->count();

        return view('book.detail', compact('book', 'relatedBooks', 'soldCount'));
    }
}

app/View/Components/DashboardLayout.php
<?php

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class DashboardLayout extends Component
{
    public function __construct(public string|null $pageTitle = null)
    {
        //
    }

    public function render(): View
    {
        return view('layouts.dashboard');
    }
}

resources/views/admin/book/delete.blade.php
<dialog id="deleteModal" class="modal">
    <div class="modal-box flex flex-col items-center">
        <svg class="w-28 h-28 text-error" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
        <h3 class="font-bold text-lg">Hapus Buku</h3>
        <p class="py-1 text-center">Apakah anda yakin akan menghapus buku <span id="delete-title" class="font-semibold"></span>?</p>
        <div class="mt-3 flex items-center gap-x-1">
            <form method="dialog">
                <button class="btn">Batal</button>
            </form>
            <form id="form-delete" action="{{ route('admin.book') }}" method="post">
                @csrf @method('delete')
                <button type="submit" class="btn btn-error">Hapus</button>
            </form>
        </div>
    </div>
    <form method="dialog" class="modal-backdrop">
        <button>close</button>
    </form>
</dialog>

resources/views/admin/book/form.blade.php
<x-dashboard-layout page-title="Add Book">
    <div class="card w-full p-6 bg-base-100 shadow-xl mt-2">
        <form action="{{ route('admin.book') . ($book ? '/' . $book->slug : '') }}" method="post" enctype="multipart/form-data" x-data="bookForm()">
            @csrf @if($book) @method('put') @endif
            <div class="flex gap-x-5">
                <section class="container w-1/3 mx-auto items-center">
                    <div class="max-w-sm mx-auto bg-white rounded-lg shadow-md overflow-hidden items-center">
                        <div class="px-4 py-6">
                            <div class="relative p-6 mb-4 bg-gray-100 border-dashed border-2 border-gray-400 rounded-lg items-center mx-auto text-center cursor-pointer">
                                <img id="image-preview" @if($book) src="{{ $book?->image_url }}" @endif class="absolute left-0 right-0 mx-auto origin-center inset-0 h-full">
                                <input id="image" type="file" name="image" class="hidden" accept="image/*" @change="imagePreview(event)" />
                                <label for="image" class="cursor-pointer" id="image-label">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8 text-gray-700 mx-auto mb-4">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
                                    </svg>
                                    <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-700">Upload image</h5>
                                    <p class="font-normal text-sm text-gray-400 md:px-6">Choose image size should be less than <b class="text-gray-600">2mb</b></p>
                                    <p class="font-normal text-sm text-gray-400 md:px-6">and should be in <b class="text-gray-600">JPG, PNG, or GIF</b> format.</p>
                                </label>
                            </div>
                        </div>
                    </div>
                </section>
                <div class="grid grid-cols-2 gap-3 w-2/3">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Judul Buku</span>
                        </div>
                        <input type="text" name="title" placeholder="Judul Buku" class="input input-bordered w-full max-w-xs" value="{{ $book?->title ?? old('title') }}" required/>
                    </label>
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Kategori</span>
                        </div>
                        <select class="select select-bordered" name="category_id" required>
                            <option disabled {{ $book ? '' : 'selected' }}>Pilih Kategori</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}" {{ $book?->category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </label>
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Penulis / Penerbit</span>
                        </div>
                        <input type="text" name="author" placeholder="Penerbit" class="input input-bordered w-full max-w-xs" value="{{ $book?->author ?? old('author') }}" required/>
                    </label>
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Harga</span>
                        </div>
                        <input type="number" name="price" placeholder="50000" class="input input-bordered w-full max-w-xs" value="{{ $book?->price ?? old('price') }}" required/>
                    </label>
                    <div class="col-span-2">
                        <label class="form-control w-full">
                            <div class="label">
                                <span class="label-text">File</span>
                            </div>
                            <input type="file" accept=".pdf" name="book_file" class="file-input file-input-bordered w-full" {{ $book ? '' : 'required' }} />
                            @if($book)
                                <div class="label">
                                    <span class="label-text-alt flex items-center gap-x-1 text-info">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                                        </svg>
                                        <a href="{{ route('admin.book.file', [$book->slug, Str::random(8)]) }}" target="_blank">Lihat file</a>
                                    </span>
                                </div>
                            @endif
                        </label>
                    </div>
                </div>
            </div>
            <div class="w-full mt-3">
                <label class="form-control">
                    <div class="label">
                        <span class="label-text">Deskripsi</span>
                    </div>
                    <textarea name="description" class="textarea textarea-bordered h-24" placeholder="Bio">{{ $book?->description ?? old('description') }}</textarea>
                </label>
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </div>
        </form>
    </div>

    @push('scripts')
        <script>
            const imageInput = document.getElementById('image')
            const imageLabel = document.getElementById('image-label')
            const imagePreview = document.getElementById('image-preview')

            imageInput.addEventListener('click', (event) => {
                event.stopPropagation();
            });

            function bookForm() {
                return {
                    imagePreviewEvent: {{ $book ? 'true' : 'false' }},
                    init() {
                        if (this.imagePreviewEvent) {
                            imagePreview.addEventListener('click', () => {
                                imageInput.click();
                            });
                        }
                    },
                    imagePreview(event) {
                        if (event.target.files.length > 0) {
                            imagePreview.src = URL.createObjectURL(event.target.files[0]);
                            imagePreview.style.display = 'block';
                            imageLabel.classList.add('opacity-0')

                            if (!this.imagePreviewEvent) {
                                imagePreview.addEventListener('click', () => {
                                    imageInput.click();
                                });

                                this.imagePreviewEvent = true
                            }
                        }
                    }
                }
            }
        </script>
    @endpush
</x-dashboard-layout>

resources/views/admin/book/index.blade.php
<x-dashboard-layout page-title="Books">
    @include('admin.book.delete')
    <div class="card w-full p-6 bg-base-100 shadow-xl mt-2">
        <div class="text-xl font-semibold inline-block">
            All Books
            <form class="inline-block float-right">
                <div class="inline-block mr-2">
                    <div class="input-group  relative flex flex-wrap items-stretch w-full">
                        <input type="search" name="search" aria-label="Search" placeholder="Cari judul buku" class="input input-sm input-bordered w-full max-w-xs" value="{{ request('search') }}" required />
                    </div>
                </div>
                <button class="btn btn-primary btn-sm">Search</button>
                <a href="{{ route('admin.book.create') }}" class="btn btn-secondary btn-sm">Add Book</a>
            </form>
        </div>
        <div class="divider mt-2"></div>
        @if(session('success'))
            <div class="w-full my-2">
                <div role="alert" class="alert alert-success" x-data="{ show: true }" x-show="show">
                    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span>{{ session('success') }}</span>
                    <div>
                        <button @click="show = !show">x</button>
                    </div>
                </div>
            </div>
        @endif
        <div class='h-full w-full pb-6 bg-base-100'>
            <div class="overflow-x-auto w-full">
                <table class="table w-full">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Author</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($books->items() as $book)
                        <tr>
                            <td>
                                <div class="flex items-center gap-x-3">
                                    <div class="w-20">
                                        <img class="w-full" src="{{ $book->image_url }}" alt="{{ $book->title }}">
                                    </div>
                                    <div class="font-bold text-wrap">{{ $book->title }}</div>
                                </div>
                            </td>
                            <td>{{ $book->category->name }}</td>
                            <td class="text-nowrap">{{ $book->author }}</td>
                            <td class="text-nowrap">{{ rupiah($book->price) }}</td>
                            <td>
                                <div class="flex gap-x-1 items-center">
                                    <div class="tooltip tooltip-top" data-tip="Show File">
                                        <a href="{{ route('admin.book.file', [$book->slug, Str::random(8)]) }}" target="_blank" class="btn btn-sm">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" /><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                            </svg>
                                        </a>
                                    </div>
                                    <div class="tooltip tooltip-top" data-tip="Edit">
                                        <a href="{{ route('admin.book.edit', $book->slug) }}" class="btn btn-sm btn-info">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                                            </svg>
                                        </a>
                                    </div>
                                    <div class="tooltip tooltip-top" data-tip="Delete">
                                        <button class="btn btn-sm btn-warning" onclick="confirmDelete('{{ $book->title }}', '{{ $book->slug }}')">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div class="mt-5">
                {{ $books->links('components.admin-pagination') }}
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            const deleteForm = document.getElementById('form-delete')
            const deleteTitle = document.getElementById('delete-title')

            function confirmDelete(title, slug) {
                deleteForm.setAttribute('action', '{{ route('admin.book') }}/' + slug)
                deleteTitle.innerText = title
                deleteModal.showModal()
            }
        </script>
    @endpush
</x-dashboard-layout>