routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UserController::class, 'index'])->name('user');

Route::get('/books', [BookController::class, 'index'])->name('book');
Route::get('/books/create', [BookController::class, 'create'])->name('book.create');
Route::post('/books', [BookController::class, 'store']);
Route::get('/books/{book:slug}___{randomStr}/file', [BookController::class, 'file'])->name('book.file');
Route::get('/books/{book:slug}/edit', [BookController::class, 'edit'])->name('book.edit');
Route::put('/books/{book:slug}', [BookController::class, 'update'])->name('book.update');
Route::delete('/books/{book:slug}', [BookController::class, 'destroy'])->name('book.delete');

Route::get('/articles', [ArticleController::class, 'index'])->name('article');
Route::get('/articles/create', [ArticleController::class, 'create'])->name('article.create');
Route::post('/articles', [ArticleController::class, 'store']);
Route::get('/articles/{article:slug}/edit', [ArticleController::class, 'edit'])->name('article.edit');
Route::put('/articles/{article:slug}', [ArticleController::class, 'update'])->name('article.update');
Route::delete('/articles/{article:slug}', [ArticleController::class, 'destroy'])->name('article.delete');

Route::get('/orders', [OrderController::class, 'index'])->name('order');
Route::get('/orders/{order:invoice}', [OrderController::class, 'show'])->name('order.show');
Route::post('/orders/{order:invoice}/confirm', [OrderController::class, 'confirmPayment'])->name('order.confirm');

routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MyBookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::view('/privasi', 'privasi')->name('privasi');

Route::get('/buku', [BookController::class, 'index'])->name('book');
Route::get('/buku/query', [BookController::class, 'query'])->name('book.query');
Route::get('/buku/{book:slug}', [BookController::class, 'show'])->name('book.detail');

Route::get('/berita', [ArticleController::class, 'index'])->name('article');
Route::get('/berita/{article:slug}', [ArticleController::class, 'show'])->name('article.show');

Route::middleware('auth')->group(function () {
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add/{book:slug}', [CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/remove/{book:slug}', [CartController::class, 'remove'])->name('cart.remove');

//    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('checkout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/user', [DashboardController::class, 'user'])->name('dashboard.user');

    Route::get('/kelola/buku-saya', [MyBookController::class, 'index'])->name('my-book');
    Route::get('/kelola/buku-saya/{id}___{randomStr}/file', [MyBookController::class, 'file'])->name('my-book.file');
    Route::get('/kelola/buku-saya/{id}/view', [MyBookController::class, 'view'])->name('my-book.view');

    Route::get('/kelola/transaksi', [TransactionController::class, 'index'])->name('transaction');
    Route::get('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'detail'])->name('transaction.detail');
    Route::post('/kelola/transaksi/{order:invoice}', [TransactionController::class, 'payment']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile');
    Route::put('/profile', [ProfileController::class, 'update']);
});

Route::middleware('admin')
    ->prefix('admin')
    ->name('admin.')->group(function () {
        require __DIR__ . '/admin.php';
    });

require __DIR__ . '/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-theme="emerald">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ isset($title) ? $title . ' - ' : '' }}{{ config('app.name', 'Buku Digital Nusantara') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet"/>

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="font-sans antialiased">
    <div class="min-h-screen bg-white">
        @include('layouts.navigation')

        <main>
            {{ $slot }}
        </main>

        @include('layouts.footer')
    </div>
    @stack('scripts')
</body>
</html>

resources/views/layouts/dashboard-navbar.blade.php
<div class="navbar sticky top-0 bg-[#f8f9fa] dark:bg-base-200 z-10 shadow-md" x-data="{currentTheme: localStorage.getItem('theme')}">
    <div class="flex-1">
        <label for="left-sidebar-drawer" class="btn btn-primary drawer-button lg:hidden">
            <svg class="w-5 h-5 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
        </label>
        <h1 class="text-2xl font-semibold ml-2">{{ $pageTitle }}</h1>
    </div>
    <div class="flex-none ">
        <label class="swap ">
            <input type="checkbox"/>
            <svg data-set-theme="emerald" data-act-class="ACTIVECLASS" class="fill-current w-6 h-6" :class="currentTheme === 'dark' ? 'swap-on' : 'swap-off'" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
            </svg>
            <svg data-set-theme="dark" data-act-class="ACTIVECLASS" class="fill-current w-6 h-6" :class="currentTheme === 'emerald' ? 'swap-on' : 'swap-off'" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
            </svg>
        </label>

        <div class="dropdown dropdown-end mx-4">
            <label tabindex="0" class="flex items-center flex-nowrap cursor-pointer w-full avatar">
                <div class="w-8 rounded-full bg-base-300">
                    <img class="" src="{{ Vite::asset('resources/img/avatar.webp') }}" alt="profile" />
                </div>
                <span class="font-light ml-2 mr-1">Hi, {{ Auth::user()->name }}</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                </svg>
            </label>
            <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                <span class="block px-4 my-2 text-xs font-bold">{{ Auth::user()->is_admin ? 'ADMIN' : 'PEMBACA' }}</span>
                <li class="justify-between">
                    <a href="{{ route('dashboard') }}" class="flex items-center gap-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
                        </svg> Dashboard
                    </a>
                </li>
                <li class="justify-between">
                    <a href="{{ route('profile') }}" class="flex items-center gap-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                        </svg> Profile
                    </a>
                </li>
                <div class="divider mt-0 mb-0"></div>
                <li>
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf
                        <a class="flex items-center gap-x-2 text-error" href="{{route('logout')}}" onclick="event.preventDefault(); this.closest('form').submit();">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
                            </svg>
                            Logout
                        </a>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/layouts/dashboard-sidebar.blade.php
<div class="drawer-side z-30 shadow-lg">
    <label for="left-sidebar-drawer" class="drawer-overlay"></label>
    <ul class="menu pt-2 w-80 bg-base-100 min-h-full text-base-content">
        <button class="btn btn-ghost bg-base-300  btn-circle z-50 top-0 right-0 mt-4 mr-2 absolute lg:hidden" onclick="document.getElementById('left-sidebar-drawer').click()">
            <svg class="w-5 h-5 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
        </button>
        <li class="mb-2 font-semibold text-xl">
            <a href="{{ route('home') }}" ><img class="mask mask-squircle w-16" src="{{ Vite::asset('resources/img/footer-logo.png') }}" alt="Buku Digital Nusantara Logo"/>BDN</a>
        </li>
        <h2 class="menu-title">Dashboard</h2>
        <li>
            <a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
                </svg> Dashboard
                @if(request()->routeIs('dashboard'))
                    <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                @endif
            </a>
        </li>
        @if(auth()->user()->is_admin)
            <li>
                <a href="{{ route('dashboard.user') }}" class="{{ request()->routeIs('dashboard.user') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
                    </svg> Dashboard Pembaca
                    @if(request()->routeIs('dashboard.user'))
                        <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                    @endif
                </a>
            </li>
            <h2 class="menu-title">Admin</h2>
            <ul>
                <li>
                    <a href="{{ route('admin.user') }}" class="{{ request()->routeIs('admin.user') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z" />
                        </svg> Users
                        @if(request()->routeIs('admin.user'))
                            <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                        @endif
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.book') }}" class="{{ request()->routeIs('admin.book*') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
                        </svg> Books
                        @if(request()->routeIs('admin.book*'))
                            <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                        @endif
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.article') }}" class="{{ request()->routeIs('admin.article*') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 0 1-2.25 2.25M16.5 7.5V18a2.25 2.25 0 0 0 2.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 0 0 2.25 2.25h13.5M6 7.5h3v3H6v-3Z" />
                        </svg> News
                        @if(request()->routeIs('admin.article*'))
                            <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                        @endif
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.order') }}" class="{{ request()->routeIs('admin.order*') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 0 0-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 0 0-16.536-1.84M7.5 14.25 5.106 5.272M6 20.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Zm12.75 0a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
                        </svg>
                        <span>Orders</span>
                        @if($order_waiting_count !== 0)
                            <span class="badge badge-primary">{{ $order_waiting_count }}</span>
                        @endif
                        @if(request()->routeIs('admin.order*'))
                            <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                        @endif
                    </a>
                </li>
            </ul>
        @endif

        <!-- Readers Menu -->
        <h2 class="menu-title">Pembaca</h2>
        <ul>
            <li>
                <a href="{{ route('my-book') }}" class="{{ request()->routeIs('my-book') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
                    </svg> Buku Saya
                    @if(request()->routeIs('my-book'))
                        <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                    @endif
                </a>
            </li>
            <li>
                <a href="{{ route('transaction') }}" class="{{ request()->routeIs('transaction*') ? 'font-semibold bg-base-200' : 'font-normal' }}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg> Riwayat Pembelian
                    @if(request()->routeIs('transaction*'))
                        <span class="absolute inset-y-0 left-0 w-1 rounded-tr-md rounded-br-md bg-primary " aria-hidden="true"></span>
                    @endif
                </a>
            </li>
        </ul>
    </ul>
</div>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Admin - {{ config('app.name', 'Buku Digital Nusantara') }}</title>

    <!-- Scripts -->
    @trixassets
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="font-sans antialiased m-0">
<div class="drawer lg:drawer-open">
    <input id="left-sidebar-drawer" type="checkbox" class="drawer-toggle"/>
    <div class="drawer-content flex flex-col">
        @include('layouts.dashboard-navbar')
        <main class="flex-1 h-screen overflow-y-auto md:pt-4 pt-4 px-6  bg-base-200">
            <div class="min-h-[calc(100vh-250px)]">
                {{ $slot }}
            </div>

            <div class="h-16"></div>
            <p class="text-sm text-center mb-4 mt-auto">
                Buku Digital Nusantara &copy;{{ date('Y') }} <span class="font-bold text-3xl mx-2">.</span> All Rights Reserved.
            </p>
        </main>
    </div>
    @include('layouts.dashboard-sidebar')
</div>

<script src="https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js"></script>
@stack('scripts')
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased">
        <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
            <div>
                <a href="/">
                    <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
                </a>
            </div>

            <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
                {{ $slot }}
            </div>
        </div>
    </body>
</html>